##
## Unit Tests
##
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - uses: actions/checkout@v4
     
      - name: go build
        run: |
          go build ./...
    
      - name: go test
        run: |
          go test -v -coverprofile=profile.cov $(go list ./... | grep -v /examples/)
        env:
          ## GOPATH required to build serverless app inside unittest
          GOPATH: /home/runner/go
          GOCACHE: /home/runner/.cache/go-build
          GOMODCACHE: /home/runner/go/pkg/mod

      - uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: profile.cov
